### ISSUE TITLE
Multiple Choice

### ISSUE THREAD

**Issue by ffsb07** [hwgilbert16/scholarsome#71]
1. SET will not be created if it only contains 1 CARD
- For someone try to work things around, like how things works, it would take time
- For the sake of trying out one configuration at a time, creator will lessen its struggle, whenever the creator is happy with the result, he/she will just repeat the configuration to his/her CARDS

2. When creating cards there was no option for type of exam.
- By default on flashcards (based on my observation), when flashcards is clicked, TERM will contain the the questions and choices while DEFENITION will have the answer, and vice versa.
- When quiz was chosen, you'll be prompted to chose a type of exam, WRITTEN, TRUE/FALSE, MULTIPLE CHOICE. 
- Multiple choice is only available if you have 4 cards + unless it is grayed out.
- If 4 cards are created, Multiple choice is available

- ISSUE: Multiple choice is only available for 4 cards +
- ISSUE: Multiple choice are randomized, jumping out from card to card
- ISSUE: Listing items when tab is hit, it will change its format (e.g. number list > letter list), after saving, letter is not displayed, instead it displays numbers
- 

is it possible if
1. SET can be created even 1 CARD is created (for testing configurations)
2. TERM and DEFINITION container should have an option for exam type (written, T/F, Multiple Choice)
3. Fix listing options
![image_2023-11-24_080619613](https://github.com/hwgilbert16/scholarsome/assets/151885689/c556f753-e5cd-4a67-8a1a-d751f60c3d85)
![image_2023-11-24_080655512](https://github.com/hwgilbert16/scholarsome/assets/151885689/4126579d-e639-43c0-acfc-14e435e00794)
![image_2023-11-24_080825053](https://github.com/hwgilbert16/scholarsome/assets/151885689/20444d37-fe42-4f31-969f-7ee015de1063)
![image_2023-11-24_080857568](https://github.com/hwgilbert16/scholarsome/assets/151885689/ae250e56-23fb-43d2-b57f-92f5aa3de279)

**Comment by hwgilbert16** [comment]
I'll go through these one by one as most of these are topics that just need to be explained better in our usage section of the handbook (https://scholarsome.com/handbook/usage/overview/).

> SET will not be created if it only contains 1 CARD

Oversight on our part. The API checks whether the request to create a set contains greater than 1 card (>) not greater than or equal to one card (>=). This is something that will be changed.

> When creating cards there was no option for type of exam.

The issues listed under this umbrella are things that need to be explained better. Let me clarify how sets are designed to be used.

Sets are designed to mimic flashcards almost identically. When you create a card, you are not creating a question - you are creating a term that is paired to a definition. For example, in the example shown in the readme, there is a set for US state capitals. The term is the state, and the definition is the capital of that state. Sets are collections of these cards.

What it seems you are trying to do is create questions in cards. This should be explained better in our documentation that this is not how cards are meant to be created. Quizzes are intended to work by designating a card side (either term or definition) as the side that will be presented to the user, the side that will be the "question" that is asked. Assuming term is the "question" side, for the multiple choice question type, the application selects three random definitions to show alongside the correct definition for this card. You can infer how the other two types of questions work.

Quizzes are generated from sets - you do not need to make your own questions within the sets.

> By default on flashcards (based on my observation), when flashcards is clicked, TERM will contain the the questions and choices while DEFENITION will have the answer, and vice versa.

This can be changed within the flashcard configuration.

> Multiple choice is only available if you have 4 cards + unless it is grayed out.

This is as expected, as there must be at least 4 options available per question.

> ISSUE: Listing items when tab is hit, it will change its format (e.g. number list > letter list), after saving, letter is not displayed, instead it displays numbers

The priority has been to allow tabbing between the two text editors for ease of mass card creation. Still trying to get this nailed down, this is a bug and not expected behavior.

> Fix listing options

Are you saying the formatting of lists after being created? This is a bug, the list should retain its formatting after being created. This is something being looked into.

Hope that answered your questions.

**Comment by ffsb07** [comment]
Thank you for the quick prompt!
I got a better understanding how flashcards and quizzes works!
